<?php

/**
 * City From Myanmar
 *
 
 */
global $places;

$places['MM'] = array(
	'AYA' => array(
		'Bogale',
        'Danubyu',
        'Dedaye',
        'Einme',
        'Hinthada',
        'Ingapu',
        'Kangyidaunt',
        'Kyaiklat',
        'Kyangin',
        'Kyaunggon',
        'Kyonpyaw',
        'Labutta',
        'Lemyethna',
        'Maubin',
        'Mawlamyinegyun',
        'Myanaung',
        'Myaungmya',
        'Ngapudaw',
        'Nyaungdon',
        'Pantanaw',
        'Pathein',
        'Pyapon',
        'Thabaung',
        'Wakema',
        'Yegyi',
        'Zalun'
	),
	'BGE' => array(
        'Bago',
        'Daik-U',
        'Kawa',
        'Kyaukkyi',
        'Kyauktaga',
        'Nyaunglebin',
        'Oktwin',
        'Phyu',
        'Shwegyin',
        'Tantabin',
        'Taungoo',
        'Thanatpin',
        'Waw',
        'Yedashe'
    ),
'BGW' => array(
    'Gyobingauk',
    'Letpadan',
    'Minhla',
    'Monyo',
    'Nattalin',
    'Okpho',
    'Padaung',
    'Pauk Kaung',
    'Paungde',
    'Pyay',
    'Shwedaung',
    'Thayarwady',
    'Thegon',
    'Zigon',

    ),
    'CHIN' => array(
        'Falam',
        'Hakha',
        'Htantlang',
        'Kanpetlet',
        'Madupi',
        'Mindat',
        'Paletwa',
        'Tiddim',
        'Tonzang'
    
        ),
    'KACHIN' => array(
        'Bhamo',
        'Chipwi',
        'Hpakan',
        'Injangyang',
        'Kawnglanghpu',
        'Machanbaw',
        'Mansi',
        'Mogaung',
        'Mohnyin',
        'Momauk',
        'Myitkyina',
        'Nogmung',
        'Puta-O',
        'Shwegu',
        'Sumprabum',
        'Tanai',
        'Tsawlaw',
        'Waingmaw'
        
    ),
    'KAYAH' => array(
        'Bawlakhe',
        'Demoso',
        'Hpasawng',
        'Hpruso',
        'Loikaw',
        'Mese',
        'Shadaw'
        
    ),
    'KAYIN' => array(
        'Hlaingbwe',
        'Hpa-An',
        'Hpapun',
        'Kawkareik',
        'Kyain Seikgyi',
        'Myawaddy',
        'Thandaung'
        
    ),
    'MAGWAY' => array(
        'Aunglan',
        'Chauk',
        'Gangaw',
        'Kamma',
        'Magway',
        'Minbu',
        'Mindon',
        'Minhla',
        'Myaing',
        'Myothit',
        'Natmauk',
        'Ngape',
        'Pakokku',
        'Pauk',
        'Pwintbyu',
        'Salin',
        'Saw',
        'Seikphyu',
        'Sidoktaya',
        'Sinbaungwe',
        'Taungdwingyi',
        'Thayet',
        'Tilin',
        'Yenangyaung',
        'Yesagy'
        
    ),
    'MDY' => array(
        'Amarapura',
        'Aungmyaythazan',
        'Chanayethazan',
        'Chanmyathazi',
        'Kyaukpadaung',
        'Kyaukse',
        'Lewe',
        'Madaya',
        'Mahaaungmyay',
        'Mahlaing',
        'Meiktila',
        'Mogoke',
        'Myingyan',
        'Myittha',
        'Natogyi',
        'Ngazun',
        'Nyaung-U',
        'Patheingyi',
        'Pyawbwe',
        'Pyigyitagon',
        'Pyinmana',
        'Pyinoolwin',
        'Singu',
        'Sintgaing',
        'Tada-U',
        'Tatkon',
        'Taungtha',
        'Thabeikkyin',
        'Thazi',
        'Wundwin',
        'Yamethin',
        
    ),
    'MON' => array(
        'Bilin',
        'Chaungzon',
        'Kyaikmaraw',
        'Kyaikto',
        'Mawlamyine',
        'Mudon',
        'Paung',
        'Thanbyuzayat',
        'Thaton',
        'Ye',    
    ),
    'KAKHINE' => array(
        'Ann',
        'Buthidaung',
        'Gwa',
        'Kyaukpyu',
        'Kyauktaw',
        'Maungdaw',
        'Minbya',
        'Mrauk-U',
        'Munaung',
        'Myebon',    
        'Pauktaw',    
        'Ponnagyun',    
        'Ramree',    
        'Rathedaung',    
        'Sittwe',    
        'Thandwe',    
        'Toungup',    
    ),
    'SAGAING' => array(
        'Ayadaw',
        'Banmauk',
        'Budalin',
        'Chaung-U',
        'HkamtiHomalin',
        'Indaw',
        'Kale',
        'Kalewakanbalu',
        'Kani',
        'Katha',
        'Kawlin',
        'Khin-U',
        'Kyunhla',
        'Lahe',
        'LayShi',
        'Mawlaik',
        'Mingin',
        'Monywa',
        'Myaung',
        'Myinmu',
        'Nanyun',
        'Pale',
        'Paungbyin',
        'Pinlebu',
        'Sagaing',
        'Salingyi',
        'Shwebo',
        'Tabayin',
        'Tamu',
        'Taze',
        'Tigyaing',
        'Wetlet',
        'Wuntho',
        'Ye-U',
        'Yinmabin',
    ),
    'SHAN_E' => array(
        'Kengtung',
        'Matman',
        'Monghpyak',
        'Monghsat',
        'Mongkhet',
        'Mongla',
        'Mongping',
        'Mongton',
        'Mongyang',
        'Mongyawng',
        'Tachileik',
    ),
    'SHAN_N' => array(
        'Hopang',
        'Hseni',
        'Hsipaw',
        'Konkyan',
        'Kunlong',
        'Kutkai',
        'Kyuakme',
        'Lashio',
        'Laukkaing',
        'Mabein',
        'Manton',
        'Mongmao',
        'Mongmit',
        'Mongyai',
        'Muse',
        'Namhsan',
        'Namphan',
        'Namtu',
        'Nanhkan',
        'Nawnghkio',
        'Pangsang',
        'Pangwaun',
        'Tangyan',
    ),
    'SHAN_S' => array(
        'Hopang',
        'Hsihseng',
        'Kalaw',
        'Kunhing',
        'Kyethi',
        'Laihka',
        'Langkho',
        'Lawksawk',
        'Loilen',
        'Mawkmai',
        'Monghsu',
        'Mongkaung',
        'Mongnai',
        'Mongpan',
        'Nansang',
        'Nyaungshwe',
        'Pekon',
        'Pindaya',
        'Pinlaung',
        'Taunggyi',
        'Ywangan',
    ),
    'TANINTHARYI' => array(
        'Bokpyin',
        'Dawei',
        'Kawthoung',
        'Kyunsu',
        'Launglon',
        'Myeik',
        'Palaw',
        'Tanintharyi',
        'Thayetchaung',
        'Yebyu',
    ),
    'YANGON' => array(
        'Ahlone',
        'Bahan',
        'Botahtaung',
        'Cocokyun',
        'Dagon',
        'Dagon Myothit (East)',
        'Dagon Myothit(North)',
        'Dagon Myothit(Seikkan)',
        'Dagon Myothit(South)',
        'Dala',
        'Dawbon',
        'Hlaing',
        'Hlaingtharya',
        'Hlegu',
        'Hmawbi',
        'Htantabin',
        'Insein',
        'Kamaryut',
        'Kawhmu',
        'Kayan',
        'Kungyangon',
        'Kyauktada',
        'Kyauktan',
        'Kyeemyindaing',
        'Lanmadaw',
        'Latha',
        'Mayangone',
        'Mingaladon',
        'Mingalartaungnyunt',
        'North Okkalapa',
        'Pabedan',
        'Pazundaung',
        'Sanchaung',
        'Seikgyikanaungto',
        'Seikkan',
        'Shwepyithar',
        'South Okkalapa',
        'Taikkyi',
        'Tamwe',
        'Thaketa',
        'Thanlyin',
        'Thingangkuun',
        'Thongwa',
        'Twantay',
        'Yankin',
    ),
);
          
